#!/usr/bin/env php
<?php

define("DOWNLOAD_URL", "");

array_shift($argv);
process($argv);

/**
 * processes the installer
 */
function process($argv) {

    # No arguments, display help text
    if (0 === count($argv)) {
        displayHelp();
        exit(0);
    }

    # Run through all arguments
    foreach ($argv as $arg) {
        switch ($arg) {
            case '-h':
            case '--help':
                displayHelp();
                exit(0);
                break;
            case '-c':
            case '--check':
                exit(checkPlatform());
                break;
            case '-f':
            case '--force':
                installComposer();
                break;
            default:
                break;
        }
    }

    # No arguments, if checkPlatform() passes, install
    if (checkPlatform()) {
        installComposer();
    }

    exit(0);
}

/**
 * displays the help text
 */
function displayHelp() {
    echo <<<EOF
Composer Installer
------------------
Options
-h, --help   Display this text
-c, --check  Display the environment info
-f, --force  Forces the installation

EOF;
}

/**
 * check the platform for possible issues on running composer
 */
function checkPlatform() {
    $errors = array();

    if (version_compare(PHP_VERSION, '5.3.2', '<')) {
        $errors['php'] = PHP_VERSION;
    }

    if (!empty($errors)) {
        out("Composer detected that you have enabled some settings in your `php.ini` file that can make Composer unable to work properly.".PHP_EOL, 'error');

        echo PHP_EOL.'Make sure that you have changed options listed below:'.PHP_EOL;
        foreach ($errors as $error => $actual) {
            if ($error == 'php') {
                $text = "    PHP_VERSION (actual: {$actual})".PHP_EOL;
            }
            out($text, 'info');
        }
        echo PHP_EOL;
        return 0;
    }

    out("All settings correct for using Composer".PHP_EOL, 'success');
    return 1;
}

/**
 * installs composer to the current working directory
 */
function installComposer() {
    $installDir = getcwd();
    $file = $installDir.DIRECTORY_SEPARATOR.'composer.phar';

    if (is_readable($file)) {
        @unlink($file);
    }

    $download = copy('http://getcomposer.org/composer.phar', $file);

    out(PHP_EOL."Composer successfully installed to: " . $file, 'success');
    out(PHP_EOL."Use it: php composer.phar".PHP_EOL, 'info');
}

/**
 * colorize output
 */
function out($text, $color = null) {
    $styles = array(
        'success' => "\033[0;32m%s\033[0m",
        'error' => "\033[31;31m%s\033[0m",
        'info' => "\033[33;33m%s\033[0m"
    );

    echo sprintf(isset($styles[$color]) ? $styles[$color] : "%s", $text);
}
