#!/usr/bin/env php
<?php

define("WORKING_DIR", getcwd());

# Fix the arguments and count
array_shift($argv);

# Load everything after fixing arguments
require_once 'lib/loader.php';

if (!CommandLine::run($argv)) {
    echo <<<EOF
Usage: pf list <list_command>
       pf clone <app_id>
       pf create <create_command>
       pf delete <app_id>
       pf logout
       pf view <app_id>
       pf open <app_id>
       pf genssh
       pf whoami
       pf help [command]

LIST COMMAND

  cloud
    List all clouds

  apps <cloud_id>
    List all apps in a specific cloud

  sshkeys
    List all ssh keys

CREATE COMMAND

  app [<cloud_id>]
    Creates a new custom app. Specify a cloud id to create the app in or leave blank to create the app in the shared cloud.

EOF;
}
?>
